basePath: /api
definitions:
  er.Error:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  model.Arrears:
    properties:
      records:
        items:
          $ref: '#/definitions/model.ArrearsRecord'
        type: array
      total_amount:
        type: integer
    type: object
  model.ArrearsRecord:
    properties:
      order_no:
        type: string
      total_amount:
        type: integer
    type: object
  model.Car:
    properties:
      car_of_area:
        type: string
      car_type:
        type: string
      car_type_name:
        type: string
      distance:
        type: number
      id:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      project_id:
        type: string
      project_name:
        type: string
      seat:
        type: integer
      status:
        $ref: '#/definitions/model.CarStatus'
    type: object
  model.CarStatus:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - CarStatus_CAR_STATUS_UNSPECIFIED
    - CarStatus_CAR_STATUS_AVAILABLE
    - CarStatus_CAR_STATUS_INUSE
  model.Lease:
    properties:
      car_id:
        type: string
      car_latitude:
        type: number
      car_longitude:
        type: number
      "no":
        type: string
      status:
        $ref: '#/definitions/model.LeaseStatus'
    type: object
  model.LeaseStatus:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - LeaseStatus_LEASE_STATUS_UNSPECIFIED
    - LeaseStatus_LEASE_STATUS_ACTIVE
    - LeaseStatus_LEASE_STATUS_EXPIRED
  model.Profile:
    properties:
      access_token:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  orders.bookCarRequest:
    properties:
      circularly:
        type: boolean
      id:
        type: string
      project_id:
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact:
    email: blackhorseya@gmail.com
    name: sean.zheng
    url: https://blog.seancheng.space
  description: API for IRent
  license:
    name: GPL-3.0
    url: https://spdx.org/licenses/GPL-3.0-only.html
  title: IRent API
  version: 0.1.00
paths:
  /accounts/{id}/orders:
    post:
      consumes:
      - application/json
      description: book the car
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      - description: book car request
        in: body
        name: car
        required: true
        schema:
          $ref: '#/definitions/orders.bookCarRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Lease'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/er.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/er.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.Error'
      security:
      - ApiKeyAuth: []
      summary: Book the car
      tags:
      - Orders
  /accounts/{id}/orders/{order_id}:
    delete:
      consumes:
      - application/json
      description: cancel the order by id
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      - description: order id
        in: path
        name: order_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/er.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/er.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.Error'
      security:
      - ApiKeyAuth: []
      summary: Cancel the order by id
      tags:
      - Orders
  /v1/accounts/{id}/arrears:
    get:
      consumes:
      - application/json
      description: Get arrears list
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Arrears'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/er.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/er.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.Error'
      security:
      - ApiKeyAuth: []
      summary: Get arrears list
      tags:
      - Billing
  /v1/accounts/{id}/orders:
    get:
      consumes:
      - application/json
      description: List orders
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      - default: 1
        description: page number
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 10
        description: page size
        in: query
        maximum: 100
        minimum: 1
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Lease'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/er.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/er.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.Error'
      security:
      - ApiKeyAuth: []
      summary: List orders
      tags:
      - Orders
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: user id
        in: formData
        name: id
        required: true
        type: string
      - description: user password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Profile'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.Error'
      summary: Login
      tags:
      - Auth
  /v1/auth/me:
    get:
      consumes:
      - application/json
      description: Get me profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Profile'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/er.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/er.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.Error'
      security:
      - ApiKeyAuth: []
      summary: Get me profile
      tags:
      - Auth
  /v1/cars:
    get:
      consumes:
      - application/json
      description: List cars
      parameters:
      - default: 1
        description: page
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 10
        description: size
        in: query
        maximum: 100
        minimum: 1
        name: size
        type: integer
      - default: 0
        description: latitude
        in: query
        name: latitude
        type: number
      - default: 0
        description: longitude
        in: query
        name: longitude
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            x-total-count:
              description: total count
              type: int
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Car'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.Error'
      summary: List cars
      tags:
      - Cars
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
