cronjob:
  enabled: true
  interval: 5s

app:
  endpoint: https://irentcar-app.azurefd.net/api
  appVersion: "5.8.1"

db:
  url: "root:changeme@tcp(localhost:3306)/irent_rental?charset=utf8mb4&parseTime=True&loc=Local"
  debug: true
  conns: 100

log:
  encoding: console
  level: debug
